language: ruby

# https://github.com/travis-ci/travis-rubies/issues/82
before_install:
  gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

rvm:
  - 2.1
  - 2.7
  - 3.0
